version: '3.8'

services:
  ai-tools:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-tools-extended:latest
    container_name: ai-tools-extended
    ports:
      - "8000:8000"  # Original AI Tools API
      - "8080:8080"  # YouTube Extension API
    environment:
      # Original tool settings
      - WHISPER_MODEL=${WHISPER_MODEL:-base}
      - TTS_ENGINE=${TTS_ENGINE:-kokoro}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-500MB}
      # Extension settings
      - MAX_VIDEO_DURATION=${MAX_VIDEO_DURATION:-600}
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
      # Coolify specific
      - NODE_ENV=production
      - PORT=8000
    volumes:
      - ai_tools_media:/app/media
      - ai_tools_cache:/app/cache
      - ai_tools_temp:/tmp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      - "coolify.managed=true"
      - "coolify.version=1.0"
      - "coolify.type=service"

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD:-changeme}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - DB_TYPE=sqlite
      - N8N_USER_FOLDER=/home/node/.n8n
    volumes:
      - n8n_data:/home/node/.n8n
      - n8n_workflows:/home/node/workflows
    restart: unless-stopped
    depends_on:
      - ai-tools
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.managed=true"
      - "coolify.type=service"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "coolify.managed=true"
      - "coolify.type=service"

volumes:
  ai_tools_media:
    driver: local
  ai_tools_cache:
    driver: local
  ai_tools_temp:
    driver: local
  n8n_data:
    driver: local
  n8n_workflows:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: ai-tools-network
    driver: bridge